### PR TITLE
Add Atom feed

### PR DESCRIPTION
**Pull request by thekid**
Implements #63 using an Atom feed at `/feed/atom`, showing the 20 newest entries, each with one preview image. 

### Examples

*Feedly:*

Feedly

*Outlook:*

Outlook

### See also

* https://stackoverflow.com/questions/3489578/which-is-most-used-rss-or-atom-and-which-one-is-better-to-build-from and https://nelsonslog.wordpress.com/2022/07/22/writing-an-atom-feed-in-2022/ for my choice on Atom vs. RSS 
* https://stackoverflow.com/questions/29798315/adding-images-or-thumbnails-to-atom-1-0-entries for how to embed images in feeds.
* https://www.ietf.org/rfc/rfc4287.txt - the Atom web standard

### CODE REVIEW

**Comment by thekid** [comment]
@kiesel I've rolled out this feature - it's available at https://dialog.friebes.info/feed/atom. This [RSS Validator](https://www.rssboard.org/rss-validator/check.cgi?url=https%3A%2F%2Fdialog.friebes.info%2Ffeed%2Fatom) states it's valid, and I've tested it with Feedly and Outlook, see above screenshots. Does it work for you?

**Comment by thekid** [comment]
Oh and how might we add preview images to the feed? As `` inside the content as described [here](https://stackoverflow.com/questions/29798315/adding-images-or-thumbnails-to-atom-1-0-entries)?

**Comment by kiesel** [comment]
It works nicely - I am using feedly which you've already tried according to the screenshot earlier:)

**Comment by thekid** [comment]
Released in https://github.com/thekid/dialog/releases/tag/v2.6.0

**Pull request merged**
